on: [push]
jobs:
  cppcheck:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/c-utils-tools:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Cache CMake files
        id: cache-cmake
        uses: actions/cache@v4
        env:
          cache-name: cache-cmake
        with:
          path: ./build
          key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', '**.cmake') }}
      - name: Generate CMake cache
        if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
        run: cmake -B build -G Ninja
      - name: Cppcheck
        run: cmake --build build --target cppcheck
      - name: Upload Cppcheck Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck-report
          path: build/cppcheck_report.xml
  uncrustify:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/c-utils-tools:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Cache CMake files
        id: cache-cmake
        uses: actions/cache@v4
        env:
          cache-name: cache-cmake
        with:
          path: ./build
          key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', '**.cmake') }}
      - name: Generate CMake cache
        if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
        run: cmake -B build -G Ninja
      - name: Crust check
        run: cmake --build build --target uncrustify-check
      - name: Upload Uncrustify Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: uncrustify-report
          path: build/uncrustify-report.txt
